defaults: &defaults
  working_directory: ~/beta.thedogpaws.com
  docker:
    - image: circleci/ruby:2.4.2-jessie-node
      environment:
        BUNDLE_PATH: vendor/bundle

version: 2.0
jobs:
  bundle_dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/beta.thedogpaws.com

      # Restore bundle cache
      - restore_cache:
          keys:
          - beta.thedogpaws.com-{{ checksum "Gemfile.lock" }}
          
      - run:
          name: Update Node.js and npm
          command: |
            curl -sSL "https://nodejs.org/dist/v8.15.0/node-v8.15.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v8.15.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
      
      - run:
          name: Yarn Install
          command: yarn install

      - run:
          name: Yarn Build
          command: yarn build

      - save_cache:
          key: beta.thedogpaws.com-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/beta.thedogpaws.com/vendor/bundle

  deploy_production:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/beta.thedogpaws.com

      # Restore bundle cache
      - restore_cache:
          keys:
          - beta.thedogpaws.com-{{ checksum "Gemfile.lock" }}
          
      - run:
          name: Update Node.js and npm
          command: |
            curl -sSL "https://nodejs.org/dist/v8.15.0/node-v8.15.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v8.15.0-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash

      - run:
          name: Yarn Install
          command: yarn install

      - run:
          name: Yarn Build
          command: yarn build

      - run:
          name: Install Bundler
          command: gem update --system && gem install bundler

      - run:
          name: Bundle Install
          command: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
      
      - save_cache:
          key: beta.thedogpaws.com-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/beta.thedogpaws.com/vendor/bundle

      - run:
          name: Deployment to Server
          command: bundle exec cap production deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - bundle_dependencies
      - deploy_production:
          requires:
            - bundle_dependencies
          filters:
            branches:
              only: master